### ISSUE TITLE
YesNo causes the programs to hang on exit due to open stdio stream

### ISSUE THREAD

**Issue by edlongman** [tcql/node-yesno#4]
MWE: 
```javascript
var yesno= require('yesno');
yesno.ask('Doing this will hang program closure', false, function(ok){
  if(ok){
    console.log('The if was called');
  }
  else{
    console.log('The else was called');
  }
});
```

Calling pause on the process stream will stop the program exit hang
e.g.
```javascript
var yesno= require('yesno');
yesno.ask('Doing this will hang program closure', false, function(ok){
  process.stdin.pause();
  if(ok){
    console.log('The if was called');
  }
  else{
    console.log('The else was called');
  }
});
```

Required because the stream stays open stopping exit.

Calling `process.stdin.pause();`
Within the `once` event handler will stop this behaviour being a problem

**Comment by mreinstein** [comment]
@edlongman I believe this has been resolved by #1 

Let me know if you're still experiencing an issue and we'll re-open.
