### ISSUE TITLE
enable travis-ci

### ISSUE THREAD

**Issue by mreinstein** [tcql/node-yesno#5]
@tcql I've written some tests, runnable with `npm test`. I'd like to hook this up to travis-ci so these tests run automatically. Can you please go here and enable support? 

https://travis-ci.org/account/repositories

**Comment by mreinstein** [comment]
I can't do this from my account, it has to be done by the repository owner. It's super easy though, you just have to click a button enable support, and I can handle configuring it, etc.

**Comment by tcql** [comment]
👍 done!
