### ISSUE TITLE
Multiple questions

### ISSUE THREAD

**Issue by Jeniczech** [tcql/node-yesno#6]
Hello there, I am just wondering whether it is possible to ask multiple questions in the console? I have the following code but it prompts both questions at the same time:

const bootstrap = require('yesno');
const materialCss = require('yesno');

bootstrap.ask('Would you like to install Bootstrap?', true, function (ok) {
  if (ok) {
    console.log("Yay!");
  } else {
    console.log("Nope.");
  }
});

materialCss.ask('Would you like to install Material CSS?', true, function (ok) {
  if (ok) {
    console.log("Yay!");
  } else {
    console.log("Nope.");
  }
});

The output is: Would you like to install Bootstrap? Would you like to install Material CSS?

**Comment by mreinstein** [comment]
duplicate of #7

**Comment by mreinstein** [comment]
this is now possible as of v0.2.1. Or if you are using node versions 8+ you can use v0.3.0
